name: classcar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  daum_postcode_search: ^0.0.2
  flutter_inappwebview: ^5.7.2+3
  firebase_core: ^2.14.0
  google_maps_flutter: ^2.3.0
  url_launcher: ^6.1.12
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.3
  fluttertoast: ^8.2.2
  mask_text_input_formatter: ^2.5.0
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  http: ^1.1.0
  dotted_border: ^2.0.0+3
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/car.png
    - assets/icons/Logo_Black.svg
    - assets/icons/Logo.svg
    - assets/images/국민은행_로고.png
    - assets/images/기업은행_로고.png
    - assets/images/농협_로고.png
    - assets/images/부산은행_로고.png
    - assets/images/신한뱅크_로고.png
    - assets/images/우리은행_로고.png
    - assets/images/하나은행_로고.png
    - assets/images/kakaobank_logo.png
    - assets/images/카카오뱅크_로고.png
    - assets/images/SC제일은행_로고.png
    - assets/images/Toss_Logo.png
    - assets/images/토스뱅크_로고.png
