name: classcar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  daum_postcode_search: ^0.0.2
  flutter_inappwebview: ^5.7.2+3
  firebase_core: ^2.14.0
  google_maps_flutter: ^2.3.0
<<<<<<< HEAD
  url_launcher: ^6.1.12
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.0
=======
>>>>>>> 3c6db6074a35a5bdff360cfe25d0b9c7c58ffb74

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/car.png
