name: classcar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  daum_postcode_search: ^0.0.2
  flutter_inappwebview: ^5.7.2+3
  firebase_core: ^2.14.0
  google_maps_flutter: ^2.3.0
  url_launcher: ^6.1.12
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.3
  fluttertoast: ^8.2.2
  mask_text_input_formatter: ^2.5.0
  image_picker: ^1.0.1
  firebase_storage: ^11.2.5
  http: ^1.1.0
  dotted_border: ^2.0.0+3
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/car.png
    - assets/icons/Logo_Black.svg
    - assets/icons/Logo.svg
