// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUi3Z5lQMxVo4xdtDzSUwN3r0W-HKgpig',
    appId: '1:505038605485:web:cdcd305630f3298f8a0a24',
    messagingSenderId: '505038605485',
    projectId: 'carsharingdatabase-f3ff2',
    authDomain: 'carsharingdatabase-f3ff2.firebaseapp.com',
    storageBucket: 'carsharingdatabase-f3ff2.appspot.com',
    measurementId: 'G-X5CZKPQSH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6YScERJefk6F4T3xqWA8jgNeYKg2An60',
    appId: '1:505038605485:android:baff129fa12dd8078a0a24',
    messagingSenderId: '505038605485',
    projectId: 'carsharingdatabase-f3ff2',
    storageBucket: 'carsharingdatabase-f3ff2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQvHuHnw_RSONjaQBZD_vAu0Cydmc3JEw',
    appId: '1:505038605485:ios:7219d9f94f8da0d38a0a24',
    messagingSenderId: '505038605485',
    projectId: 'carsharingdatabase-f3ff2',
    storageBucket: 'carsharingdatabase-f3ff2.appspot.com',
    androidClientId: '505038605485-rupk947cbi5edcr9vb8aca3bjjejmfoq.apps.googleusercontent.com',
    iosClientId: '505038605485-mnsmuktatcpp2la9llm01qvkgh0un1bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.classcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQvHuHnw_RSONjaQBZD_vAu0Cydmc3JEw',
    appId: '1:505038605485:ios:7219d9f94f8da0d38a0a24',
    messagingSenderId: '505038605485',
    projectId: 'carsharingdatabase-f3ff2',
    storageBucket: 'carsharingdatabase-f3ff2.appspot.com',
    androidClientId: '505038605485-rupk947cbi5edcr9vb8aca3bjjejmfoq.apps.googleusercontent.com',
    iosClientId: '505038605485-mnsmuktatcpp2la9llm01qvkgh0un1bv.apps.googleusercontent.com',
    iosBundleId: 'com.example.classcar',
  );
}
