// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnE7hRNFJhGeMDaurlg0nfSVTblvXGti8',
    appId: '1:439982033780:web:68806a64392375e6903a21',
    messagingSenderId: '439982033780',
    projectId: 'class-car-test',
    authDomain: 'class-car-test.firebaseapp.com',
    storageBucket: 'class-car-test.appspot.com',
    measurementId: 'G-T43W2H1XHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF6SHQZdGM9btlbQgtg_SMARRXBCCR_-I',
    appId: '1:439982033780:android:7b3cf46b6e4f556b903a21',
    messagingSenderId: '439982033780',
    projectId: 'class-car-test',
    storageBucket: 'class-car-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATdcUg_k4QLN-ej1G0RuAp6rfDcEVwqCM',
    appId: '1:439982033780:ios:2bec4671f5e93f15903a21',
    messagingSenderId: '439982033780',
    projectId: 'class-car-test',
    storageBucket: 'class-car-test.appspot.com',
    iosClientId: '439982033780-ckcgj5vf271avgcbn2ad7oehftb2jksm.apps.googleusercontent.com',
    iosBundleId: 'com.example.classcar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATdcUg_k4QLN-ej1G0RuAp6rfDcEVwqCM',
    appId: '1:439982033780:ios:2bec4671f5e93f15903a21',
    messagingSenderId: '439982033780',
    projectId: 'class-car-test',
    storageBucket: 'class-car-test.appspot.com',
    iosClientId: '439982033780-ckcgj5vf271avgcbn2ad7oehftb2jksm.apps.googleusercontent.com',
    iosBundleId: 'com.example.classcar',
  );
}
